---
- hosts: '{{ target }}'
  vars_files:
      - vars.yml
  remote_user: root

  tasks:
  - name: locale setup (Debian)
    # Configure timezone and locale
    command: "{{ item }}"
    with_items:
      - sh -c 'echo "Europe/Moscow" > /etc/timezone'
      - dpkg-reconfigure -f noninteractive tzdata
      - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
      - sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen
      - sh -c 'echo "LANG=\"en_GB.UTF-8\"" > /etc/default/locale'
      - dpkg-reconfigure --frontend=noninteractive locales
      - update-locale LANG=en_GB.UTF-8
    when: ansible_distribution == "Debian"

  - name: locale setup (Ubuntu)
    # Configure timezone and locale
    command: "{{ item }}"
    with_items:
      - sh -c 'echo "Europe/Moscow" > /etc/timezone'
      - dpkg-reconfigure -f noninteractive tzdata
      - locale-gen en_US.UTF-8
      - locale-gen en_GB.UTF-8
      - update-locale LANG=en_GB.UTF-8
    when: ansible_distribution == "Ubuntu"

  - name: restart rsyslog to update timezone and datetime
    service: name=rsyslog state=restarted

  - name: Install system packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: '{{ system_packages }}'

